// <auto-generated />
using GraphQLWithEFCore.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLWithEFCore.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230611110248_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLWithEFCore.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Shakib",
                            Roll = "1001"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Rahat",
                            Roll = "1002"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rohit",
                            Roll = "1003"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Musfiq",
                            Roll = "1004"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ratan",
                            Roll = "1005"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
